services:
  db:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: saas
    volumes:
      - saas_platform_postgres_data:/bitnami/postgresql

  # db_test:
  #   image: bitnami/postgresql:latest
  #   ports:
  #     - 5433:5432
  #   environment:
  #     POSTGRES_USER: docker
  #     POSTGRES_PASSWORD: docker
  #     POSTGRES_DB: saas_test
  #   volumes:
  #     - saas_platform_test_postgres_data:/bitnami/postgresql

volumes:
  saas_platform_postgres_data:
  # saas_platform_test_postgres_data:
