### Environment variables
@baseUrl = http://localhost:3001/api/v1
@email = test@example.com
@firstName = Caio Trevisan
@lastName = Trevisan
@password = password123
@providerType = PASSWORD
@refreshToken = {{refreshTokenResponse.response.body.refreshToken}}
@accessToken = {{loginResponse.response.body.accessToken}}

### Sign Up
# @name signupResponse
POST {{baseUrl}}/auth/sign-up
Content-Type: application/json

{
  "email": "{{email}}",
  "firstName": "{{firstName}}",
  "lastName": "{{lastName}}",
  "password": "{{password}}",
  "providerType": "{{providerType}}"
}

### Verify Email
# @name verifyEmailResponse
POST {{baseUrl}}/auth/verify-email
Content-Type: application/json

{
  "userId": "cm9ct1dpl00009ucdqf88q46y",
  "token": "ZauwM21cIXPMsto6oowf"
}

### Login
# @name loginResponse
POST {{baseUrl}}/auth/sign-in
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Get User Profile
GET {{baseUrl}}/users/me
Authorization: Bearer {{accessToken}}

### Refresh Token
# @name refreshTokenResponse
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### Change Password
POST {{baseUrl}}/auth/change-password
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "currentPassword": "{{password}}",
  "newPassword": "newPassword123"
}

### Forgot Password
# @name forgotPasswordResponse
POST {{baseUrl}}/auth/forgot-password
Content-Type: application/json

{
  "email": "{{email}}"
}

### Reset Password
POST {{baseUrl}}/auth/reset-password
Content-Type: application/json

{
  "token": "{{forgotPasswordResponse.response.body.resetToken}}",
  "password": "{{password}}"
}

### Logout (Optional, if implemented)
POST {{baseUrl}}/auth/logout
Authorization: Bearer {{accessToken}}