import { z } from "zod";

export enum ErrorCode {
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  UNAUTHORIZED = "UNAUTHORIZED",

  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  INVALID_PASSWORD = "INVALID_PASSWORD",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  UNEXPECTED_ERROR = "UNEXPECTED_ERROR",
  VERIFICATION_CODE_CREATION_FAILED = "VERIFICATION_CODE_CREATION_FAILED",
  VERIFICATION_CODE_INVALID = "VERIFICATION_CODE_INVALID",
  VERIFICATION_FAILED = "VERIFICATION_FAILED",
  VERIFICATION_CODE_RATE_LIMIT = "VERIFICATION_CODE_RATE_LIMIT",
  USER_NOT_VERIFIED = "USER_NOT_VERIFIED",
  ACCOUNT_NOT_FOUND = "ACCOUNT_NOT_FOUND",
  INVALID_PROVIDER = "INVALID_PROVIDER",
  INVALID_REQUEST = "INVALID_REQUEST",
  EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
  REFRESH_TOKEN_INVALID = "REFRESH_TOKEN_INVALID",
  INVALID_OTP_METHOD = "INVALID_OTP_METHOD",
  MEMBERSHIP_INVITE_ALREADY_EXISTS = "MEMBERSHIP_INVITE_ALREADY_EXISTS",
  EMAIL_ALREADY_VERIFIED = "EMAIL_ALREADY_VERIFIED",
}

export const errorCodesSchema = z.nativeEnum(ErrorCode);
