import { z } from "zod";

export enum Roles {
  PLATFORM_OWNER = "PLATFORM_OWNER",
  PLATFORM_ADMIN = "PLATFORM_ADMIN",
  PLATFORM_USER = "PLATFORM_USER",
  ORGANIZATION_OWNER = "ORGANIZATION_OWNER",
  ORGANIZATION_ADMIN = "ORGANIZATION_ADMIN",
  ORGANIZATION_USER = "ORGANIZATION_USER",
  USER = "USER",
}

export const rolesSchema = z.nativeEnum(Roles);
